name = "KolayXport"
client_id = "f1c1b63632b2d02f5520b3e96113f0e1"
application_url = "https://kolayxport.com/api/integrations/shopify/install"
embedded = false

[auth]
redirect_urls = ["https://kolayxport.com/api/integrations/shopify/callback"]

[webhooks]
api_version = "2024-10"

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://kolayxport.com/api/shopify/webhooks/compliance"
  customer_data_request_url = "https://kolayxport.com/api/shopify/webhooks/compliance"
  shop_deletion_url = "https://kolayxport.com/api/shopify/webhooks/compliance"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "https://kolayxport.com/api/shopify/webhooks/app-uninstalled"

[access_scopes]
scopes = "read_orders,read_products,write_products,read_inventory,write_inventory"
