name: Auto Sync Orders

on:
  schedule:
    - cron: '*/15 * * * *' # Every 15 minutes

jobs:
  auto-sync-orders:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run auto-sync script
        env:
          KOLAYXPORT_BASE_URL: ${{ secrets.KOLAYXPORT_BASE_URL }}
        run: node scripts/auto-sync-all-users.js
